name: Playwright Tests
on:
  pull_request:
    branches: krupali-yadav
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        app-name: ["hotel", "guest"]
    name: Test ${{matrix.app-name}} App
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/${{matrix.app-name}}/playwright-report/
          retention-days: 30
